# Generated by Django 3.1.4 on 2020-12-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_identifier', models.CharField(max_length=7000)),
                ('to_url', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
