# Generated by Django 3.1.4 on 2020-12-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirectitem',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
