# Generated by Django 3.1.4 on 2021-01-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0002_redirectitem_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirectitem',
            name='qr_data_utf8',
            field=models.CharField(default='fake', max_length=7000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redirectitem',
            name='secret',
            field=models.CharField(default='secret', max_length=10),
            preserve_default=False,
        ),
    ]
