# Generated by Django 3.1.8 on 2023-07-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0004_redirectitem_errorcorrectionlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirectitem',
            name='internal_item_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='redirectitem',
            name='mistakes',
            field=models.CharField(default='', max_length=7000),
        ),
        migrations.AddField(
            model_name='redirectitem',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
